### PR TITLE
add new textures, change old ones and delete unnecessary copies, add …

### PR DESCRIPTION
**Pull request by Haui1112**
…changelog

### CODE REVIEW

**Comment by newtoallofthis123** [comment]
Thanks a lot @Haui1112!!
I will merge it as soon as I test it

**Comment by newtoallofthis123** [comment]
Seems awesome!
Thanks @Haui1112!

**Comment by Haui1112** [comment]
Thanks. I'm playing fairly regularly now and if something pops up I just exchange it while I go.
I would love to make a MC "inspired" texturepack to get away from the legal issues. You interested?

**Comment by newtoallofthis123** [comment]
Oh yeah that would be cool!

**Pull request merged**
